version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/MediCare
      NODE_ENV: production
    restart: unless-stopped

  mongo:
    image: mongo:7-alpine
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
