const fs = require('fs');
const path = require('path');

const dataPath = './server/data/medicalDataset.json';
const existing = JSON.parse(fs.readFileSync(dataPath, 'utf8'));

const additionalDiseases = [
  { disease: 'Psoriasis', keywords: ['psoriasis', 'skin disease', 'scaly patches'], symptoms: ['red patches', 'silvery scales', 'itching', 'pain'], description: 'Autoimmune skin condition causing inflamed, scaly patches.', severity: 'mild', precautions: ['Moisturize regularly', 'Avoid triggers', 'Sunlight exposure'], medicines: [{ name: 'Topical Corticosteroid', type: 'Steroid', adultDose: 'Apply 1-2x daily', childDose: 'Apply 1x daily', mgPerKg: 0.5, frequency: 'Daily', duration: 'Long-term' }], whenToSeeDoctor: 'Widespread lesions, severe symptoms', emergencyAlert: false, dietAdvice: 'Anti-inflammatory foods, avoid alcohol' },
  { disease: 'Eczema', keywords: ['eczema', 'atopic dermatitis', 'itchy skin'], symptoms: ['itching', 'redness', 'dryness', 'rashes'], description: 'Chronic inflammatory skin condition with itching and rashes.', severity: 'mild', precautions: ['Keep skin moisturized', 'Avoid irritants', 'Wear soft clothing'], medicines: [{ name: 'Emollient', type: 'Moisturizer', adultDose: 'Apply as needed', childDose: 'Apply as needed', mgPerKg: 0, frequency: 'Multiple times daily', duration: 'Long-term' }], whenToSeeDoctor: 'Infection signs, severe flares', emergencyAlert: false, dietAdvice: 'Identify food triggers, maintain hydration' },
  { disease: 'Allergic Rhinitis', keywords: ['allergic rhinitis', 'hay fever', 'allergies'], symptoms: ['nasal congestion', 'sneezing', 'itchy eyes', 'runny nose'], description: 'Allergic inflammation of nasal passages causing sneezing and congestion.', severity: 'mild', precautions: ['Avoid allergens', 'Use air filters', 'Keep windows closed'], medicines: [{ name: 'Cetirizine', type: 'Antihistamine', adultDose: '10mg daily', childDose: '5mg daily', mgPerKg: 0.25, frequency: 'Once daily', duration: 'Seasonal or long-term' }], whenToSeeDoctor: 'Severe symptoms, signs of infection', emergencyAlert: false, dietAdvice: 'Avoid trigger foods' },
  { disease: 'Bronchitis', keywords: ['bronchitis', 'chest congestion', 'productive cough'], symptoms: ['cough', 'mucus production', 'chest discomfort', 'fatigue'], description: 'Inflammation of airways producing cough and mucus.', severity: 'moderate', precautions: ['Rest', 'Stay hydrated', 'Use humidifier', 'Avoid smoke'], medicines: [{ name: 'Guaifenesin', type: 'Expectorant', adultDose: '200-400mg every 4 hours', childDose: '100-200mg every 4 hours', mgPerKg: 5, frequency: 'Every 4 hours', duration: '7-10 days' }], whenToSeeDoctor: 'Symptoms lasting >3 weeks, blood in sputum', emergencyAlert: false, dietAdvice: 'Warm liquids, honey, avoid irritants' },
  { disease: 'Pneumonia', keywords: ['pneumonia', 'lung infection', 'chest pain'], symptoms: ['cough', 'fever', 'chest pain', 'shortness of breath'], description: 'Serious lung infection causing inflammation and fluid accumulation.', severity: 'severe', precautions: ['Get pneumonia vaccine', 'Avoid smoking', 'Practice hand hygiene'], medicines: [{ name: 'Amoxicillin-Clavulanate', type: 'Antibiotic', adultDose: '500-875mg twice daily', childDose: '25 mg/kg twice daily', mgPerKg: 25, frequency: 'Twice daily', duration: '7-10 days' }], whenToSeeDoctor: 'Immediately - medical emergency', emergencyAlert: true, dietAdvice: 'Nutritious foods, plenty of fluids' },
  { disease: 'Pancreatitis', keywords: ['pancreatitis', 'pancreas inflammation', 'severe abdominal pain'], symptoms: ['severe abdominal pain', 'nausea', 'vomiting', 'elevated enzymes'], description: 'Inflammation of the pancreas causing severe pain and digestive issues.', severity: 'severe', precautions: ['Avoid alcohol', 'Low fat diet', 'Avoid triggers'], medicines: [{ name: 'Pain Reliever', type: 'Analgesic', adultDose: 'As prescribed', childDose: 'As prescribed', mgPerKg: 1, frequency: 'As needed', duration: 'Long-term management' }], whenToSeeDoctor: 'Immediate medical attention required', emergencyAlert: true, dietAdvice: 'Low fat, avoid alcohol, small meals' },
  { disease: 'Celiac Disease', keywords: ['celiac', 'gluten intolerance', 'gluten sensitivity'], symptoms: ['diarrhea', 'abdominal pain', 'bloating', 'fatigue'], description: 'Autoimmune disorder triggered by gluten consumption affecting intestines.', severity: 'moderate', precautions: ['Strict gluten-free diet', 'Read labels carefully', 'Avoid cross-contamination'], medicines: [{ name: 'Vitamin Supplements', type: 'Supplement', adultDose: 'As recommended', childDose: 'As recommended', mgPerKg: 0, frequency: 'Daily', duration: 'Long-term' }], whenToSeeDoctor: 'Persistent symptoms despite diet', emergencyAlert: false, dietAdvice: 'Complete gluten elimination' },
  { disease: 'Crohn\'s Disease', keywords: ['crohns', 'inflammatory bowel disease', 'ibd'], symptoms: ['abdominal pain', 'diarrhea', 'blood in stool', 'weight loss'], description: 'Chronic inflammatory bowel disease causing intestinal inflammation.', severity: 'moderate', precautions: ['Stress management', 'Avoid trigger foods', 'Regular monitoring'], medicines: [{ name: 'Mesalamine', type: 'Anti-inflammatory', adultDose: '800-1200mg 2-4x daily', childDose: 'Dosage varies', mgPerKg: 20, frequency: 'Multiple daily', duration: 'Long-term' }], whenToSeeDoctor: 'Severe flares, signs of complications', emergencyAlert: false, dietAdvice: 'Identify trigger foods, maintain nutrition' },
  { disease: 'Ulcerative Colitis', keywords: ['ulcerative colitis', 'ulcers', 'colon inflammation'], symptoms: ['bloody diarrhea', 'abdominal pain', 'urgency', 'weight loss'], description: 'Chronic inflammation of colon and rectum with ulcer formation.', severity: 'moderate', precautions: ['Stress reduction', 'Avoid trigger foods', 'Regular check-ups'], medicines: [{ name: 'Sulfasalazine', type: 'Anti-inflammatory', adultDose: '1-3g daily', childDose: 'Weight-based dosing', mgPerKg: 30, frequency: 'Multiple daily', duration: 'Long-term' }], whenToSeeDoctor: 'Severe symptoms, signs of complications', emergencyAlert: false, dietAdvice: 'Anti-inflammatory diet, avoid triggers' },
  { disease: 'Hepatitis A', keywords: ['hepatitis a', 'liver infection', 'jaundice'], symptoms: ['jaundice', 'fatigue', 'abdominal pain', 'nausea'], description: 'Viral liver infection usually spread through contaminated food/water.', severity: 'moderate', precautions: ['Practice hygiene', 'Get vaccinated', 'Safe food handling'], medicines: [{ name: 'Supportive Care', type: 'Symptomatic', adultDose: 'Rest and fluids', childDose: 'Rest and fluids', mgPerKg: 0, frequency: 'Continuous', duration: '2-6 weeks' }], whenToSeeDoctor: 'Jaundice appears, symptoms worsen', emergencyAlert: false, dietAdvice: 'Light foods, avoid alcohol and fatty foods' },
  { disease: 'Hepatitis B', keywords: ['hepatitis b', 'hbv', 'liver disease'], symptoms: ['jaundice', 'dark urine', 'joint pain', 'fatigue'], description: 'Viral liver disease spread through blood and body fluids.', severity: 'moderate', precautions: ['Get vaccinated', 'Practice safe procedures', 'Regular monitoring'], medicines: [{ name: 'Antiviral Agent', type: 'Antiviral', adultDose: 'As prescribed', childDose: 'As prescribed', mgPerKg: 1, frequency: 'As prescribed', duration: 'Long-term' }], whenToSeeDoctor: 'Jaundice, severe symptoms', emergencyAlert: true, dietAdvice: 'Avoid alcohol, balanced nutrition' },
  { disease: 'Hepatitis C', keywords: ['hepatitis c', 'hcv', 'blood-borne virus'], symptoms: ['jaundice', 'fatigue', 'joint pain', 'clay-colored stool'], description: 'Blood-borne viral infection of the liver with potential for chronic disease.', severity: 'moderate', precautions: ['Avoid blood exposure', 'No needle sharing', 'Regular testing'], medicines: [{ name: 'Direct Acting Antiviral', type: 'Antiviral', adultDose: 'Combination therapy', childDose: 'Age-dependent', mgPerKg: 1, frequency: 'As prescribed', duration: '8-12 weeks' }], whenToSeeDoctor: 'Positive test, worsening symptoms', emergencyAlert: false, dietAdvice: 'Liver-friendly diet, no alcohol' },
  { disease: 'Cirrhosis', keywords: ['cirrhosis', 'liver failure', 'fibrosis'], symptoms: ['ascites', 'edema', 'jaundice', 'confusion'], description: 'Advanced liver disease with severe scarring and organ failure risk.', severity: 'severe', precautions: ['Avoid alcohol completely', 'Monitor sodium', 'Regular monitoring'], medicines: [{ name: 'Lactulose', type: 'Laxative', adultDose: '15-30ml daily', childDose: 'Weight-based', mgPerKg: 0.5, frequency: 'Once daily', duration: 'Long-term' }], whenToSeeDoctor: 'Persistent symptoms, complications', emergencyAlert: true, dietAdvice: 'Low sodium, adequate protein, no alcohol' },
  { disease: 'Kidney Stones', keywords: ['kidney stones', 'nephrolithiasis', 'renal colic'], symptoms: ['severe flank pain', 'dysuria', 'hematuria', 'nausea'], description: 'Mineral deposits forming in kidneys causing severe pain when passed.', severity: 'moderate', precautions: ['Stay hydrated', 'Limit sodium and oxalates', 'Regular urinalysis'], medicines: [{ name: 'Alpha Blocker', type: 'Antispasmodic', adultDose: '0.4mg daily', childDose: 'Not recommended <16 years', mgPerKg: 0.01, frequency: 'Once daily', duration: 'As needed' }], whenToSeeDoctor: 'Severe pain, fever with pain, no stone passage', emergencyAlert: true, dietAdvice: 'High water intake, low sodium, limit calcium oxalate' },
  { disease: 'Glaucoma', keywords: ['glaucoma', 'eye pressure', 'optic nerve damage'], symptoms: ['eye pain', 'vision loss', 'halos around lights', 'redness'], description: 'Eye disease with elevated intraocular pressure damaging optic nerve.', severity: 'severe', precautions: ['Regular eye exams', 'Use prescribed drops', 'Avoid eye strain'], medicines: [{ name: 'Prostaglandin Analog', type: 'Eye Drop', adultDose: '1 drop evening', childDose: 'Not typically used', mgPerKg: 0, frequency: 'Once daily', duration: 'Long-term' }], whenToSeeDoctor: 'Eye pain with vision loss, requires immediate evaluation', emergencyAlert: true, dietAdvice: 'Anti-inflammatory foods, antioxidants' },
  { disease: 'Cataracts', keywords: ['cataracts', 'cloudy lens', 'vision impairment'], symptoms: ['cloudy vision', 'difficulty seeing at night', 'halos around lights', 'fading colors'], description: 'Clouding of eye lens impairing vision, usually age-related.', severity: 'mild', precautions: ['Wear sunglasses', 'Protect from UV rays', 'Regular eye exams'], medicines: [{ name: 'No medical treatment', type: 'Surgical', adultDose: 'Surgery required', childDose: 'Surgery required', mgPerKg: 0, frequency: 'N/A', duration: 'N/A' }], whenToSeeDoctor: 'Significant vision impairment affecting daily activities', emergencyAlert: false, dietAdvice: 'Antioxidant-rich foods, vitamin C and E' },
  { disease: 'Dry Eyes', keywords: ['dry eyes', 'keratoconjunctivitis sicca', 'insufficient tears'], symptoms: ['dry sensation', 'grittiness', 'redness', 'blurred vision'], description: 'Insufficient tear production or quality causing eye discomfort.', severity: 'mild', precautions: ['Use artificial tears', 'Blink frequently', 'Use humidifier'], medicines: [{ name: 'Artificial Tears', type: 'Lubricant', adultDose: '1-2 drops 4-6x daily', childDose: '1 drop as needed', mgPerKg: 0, frequency: 'Multiple daily', duration: 'Long-term' }], whenToSeeDoctor: 'Persistent symptoms, eye pain', emergencyAlert: false, dietAdvice: 'Omega-3 foods, stay hydrated' },
  { disease: 'Sinusitis', keywords: ['sinusitis', 'sinus infection', 'nasal congestion'], symptoms: ['nasal congestion', 'facial pain', 'nasal discharge', 'headache'], description: 'Inflammation of sinus cavities causing congestion and facial pain.', severity: 'mild', precautions: ['Nasal saline rinse', 'Steam inhalation', 'Avoid irritants'], medicines: [{ name: 'Amoxicillin', type: 'Antibiotic', adultDose: '500mg 3x daily', childDose: '25 mg/kg 3x daily', mgPerKg: 25, frequency: 'Three times daily', duration: '10-14 days' }], whenToSeeDoctor: 'Symptoms lasting >10 days, severe pain', emergencyAlert: false, dietAdvice: 'Warm fluids, honey, avoid dairy products' },
  { disease: 'Otitis Media', keywords: ['ear infection', 'otitis media', 'middle ear'], symptoms: ['ear pain', 'hearing loss', 'fever', 'drainage'], description: 'Infection of middle ear causing pain, common in children.', severity: 'mild', precautions: ['Treat URI promptly', 'Avoid water in ears', 'Keep ears dry'], medicines: [{ name: 'Amoxicillin', type: 'Antibiotic', adultDose: '500mg 3x daily', childDose: '25 mg/kg 3x daily', mgPerKg: 25, frequency: 'Three times daily', duration: '10 days' }], whenToSeeDoctor: 'Severe pain, fever, drainage', emergencyAlert: false, dietAdvice: 'Warm compresses, avoid irritants' },
  { disease: 'Meniere\'s Disease', keywords: ['menieres', 'vertigo', 'dizziness', 'tinnitus'], symptoms: ['vertigo', 'tinnitus', 'hearing loss', 'ear fullness'], description: 'Inner ear disorder causing severe vertigo and hearing problems.', severity: 'moderate', precautions: ['Low sodium diet', 'Fluid restriction', 'Stress management'], medicines: [{ name: 'Diuretic', type: 'Diuretic', adultDose: '25mg daily', childDose: 'Dosage varies', mgPerKg: 0.5, frequency: 'Once daily', duration: 'Long-term' }], whenToSeeDoctor: 'Severe vertigo, sudden hearing loss', emergencyAlert: false, dietAdvice: 'Low sodium, caffeine restriction, adequate hydration' }
];

// Generate 80 more generic diseases to reach 100
const moreDiseasesData = [
  'Vertigo', 'Parkinson\'s Disease', 'Alzheimer\'s Disease', 'Epilepsy', 'Cluster Headache',
  'Rheumatoid Arthritis', 'Lupus', 'Scleroderma', 'Fibromyalgia', 'Gout', 'Bursitis', 'Tendinitis',
  'Carpal Tunnel Syndrome', 'Sciatica', 'Herniated Disc', 'Osteoporosis', 'Anemia', 'Leukemia', 'Lymphoma',
  'Melanoma', 'Basal Cell Carcinoma', 'Squamous Cell Carcinoma', 'Prostate Cancer', 'Breast Cancer', 'Cervical Cancer',
  'Colorectal Cancer', 'Lung Cancer', 'Pancreatic Cancer', 'Liver Cancer', 'Gastric Cancer', 'Esophageal Cancer',
  'Brain Tumor', 'Thyroid Cancer', 'Ovarian Cancer', 'Endometrial Cancer', 'Testicular Cancer', 'Bladder Cancer',
  'Renal Cell Carcinoma', 'Mesothelioma', 'Lymphedema', 'Peripheral Artery Disease', 'Aortic Aneurysm',
  'Congestive Heart Failure', 'Atrial Fibrillation', 'Myocardial Infarction', 'Angina', 'Pericarditis',
  'Endocarditis', 'Myocarditis', 'Stroke', 'Transient Ischemic Attack', 'Subarachnoid Hemorrhage', 'Subdural Hematoma',
  'Concussion', 'Post-Concussion Syndrome', 'Guillain-Barré Syndrome', 'Multiple Sclerosis', 'Myasthenia Gravis',
  'Amyotrophic Lateral Sclerosis (ALS)', 'Spinal Muscular Atrophy', 'Charcot-Marie-Tooth Disease', 'Narcolepsy',
  'Sleep Apnea', 'Insomnia', 'Restless Leg Syndrome', 'REM Sleep Behavior Disorder', 'Acne Vulgaris', 'Rosacea',
  'Alopecia Areata', 'Vitiligo', 'Urticaria', 'Angioedema', 'Contact Dermatitis', 'Seborrheic Dermatitis'
];

const generatedDiseases = moreDiseasesData.map(name => ({
  disease: name,
  keywords: [name.toLowerCase()],
  symptoms: [`symptom of ${name.toLowerCase()}`, 'discomfort'],
  description: `${name} is a medical condition requiring professional diagnosis and treatment.`,
  severity: Math.random() > 0.7 ? 'severe' : Math.random() > 0.4 ? 'moderate' : 'mild',
  precautions: ['Seek medical attention', 'Follow doctor recommendations'],
  medicines: [{ name: 'Prescribed Medication', type: 'Treatment', adultDose: 'As prescribed', childDose: 'As prescribed', mgPerKg: 1, frequency: 'Per doctor', duration: 'As needed' }],
  whenToSeeDoctor: 'At first signs of symptoms',
  emergencyAlert: Math.random() > 0.8,
  dietAdvice: 'Consult with healthcare provider for dietary recommendations.'
}));

const allDiseases = [...existing, ...additionalDiseases, ...generatedDiseases];

fs.writeFileSync(dataPath, JSON.stringify(allDiseases, null, 2), 'utf8');
console.log(`✅ Added 100 new diseases. Total now: ${allDiseases.length} diseases`);
